setxkbmap es
setxkbmap -option caps:swapescape
xset r rate 300 50
xrandr --output Virtual-1 --mode 1920x1080
clipmenud &
dunst &
picom &
feh --no-fehbg --bg-scale /home/imágenes/fondos/Shinobu.png
exec spectrwm
