setopt autocd cdable_vars chase_dots promptsubst rmstarsilent interactive_comments

bindkey -v
tabs 4

# Aliases
alias t='gtypist esp.typ'
alias -g e='nvim'
alias ev='e ~/.config/nvim/init.vim'
alias ez='e ~/.zshrc'
alias -g exa='exa --group-directories-first'
alias -g l='exa -l'
alias -g la='exa -la'
alias ls='exa'
alias lsa='exa -a'
alias tree='exa --tree'
alias lr='tree -R'
alias lra='tree -Ra'
alias ld='exa -R | grep "\./"'
alias lda='exa -Ra | grep "\./"'
alias bat='bat --style numbers --color always --theme base16'
alias grep='grep --color=auto'
alias -g cp="cp -ir"
alias -g mv='mv -i'
alias df='df -h'
alias free='free -h'
alias psmem='ps auxf | sort -nr -k 4 | head -5'
alias pscpu='ps auxf | sort -nr -k 3 | head -5'
alias mount='sudo mount'
alias umount='sudo umount -a 2>/dev/null'
alias nf='neofetch'

alias m='mpv ~/música/*/* --shuffle'
alias mc='mpv ~/música/clásica/*/* --shuffle'
alias me='mpv ~/música/español/*/* --shuffle'
alias mi='mpv ~/música/inglés/*/* --shuffle'
alias mj='mpv ~/música/japonés/*/* --shuffle'

alias pmi='sudo pacman -S'
alias pmb='pacman -Ss'
alias pmd='sudo pacman -Rcdnsu'
alias pml='pacman -Q'
alias pmo='pacman -Q | grep'
alias pma='sudo pacman -Syyyuu'
alias pmc='sudo pacman -Scc'

alias zz='sudo shutdown -f now'
alias re='sudo shutdown -r now'

# Historial
SAVEHIST=1000
HISTSIZE=1000
HISTFILE=~/.cache/historial

# Coloreado
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_STYLES[path]=none
ZSH_HIGHLIGHT_STYLES[precommand]='fg=green'
zle_highlight=('paste:none')

# Etiqueta
autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:git:*' formats '(%m%u%c%b) '
zstyle ':vcs_info:git*+set-message:*' hooks git-untracked
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
+vi-git-untracked(){
	if [[ $(git rev-parse --is-inside-work-tree 2>/dev/null) == 'true' ]] && git status --porcelain | grep '??' &> /dev/null ; then
		hook_com[staged]+='*'
	fi
}
PS1='%B%F{4}%1~ %F{1}${vcs_info_msg_0_}%F{2}%(!.€.$)%b%f '
